
# for pigpio, use Broadcom pin numbers
# for Raspberry Pi 3 Model B, http://abyz.co.uk/rpi/pigpio/index.html#Type_3
READ_PIN: 17 # Pin to read key input from
LED_PIN: 27 # Pin for LED
BUZZER_PIN: 22 # Pin for Buzzer

BUZZER_FREQ: 320 # Frequency for Buzzer
BUZZER_DC: 30 # Duty Cycle for Buzzer Pulse Width Modulation, 0-255
BLINKER_FREQ: 10 # Frequency for LED Blinks
BLINKER_DC: 40 # Duty Cycle for Blinker Pulse Width Modulation, 0-255

WORD_DELIMETER: " " # string separator for words

KEYPRESS_THRESHOLD: 10  # ms, how long a press has to be to be recognized, for bounce
DITDAH_THRESHOLD: 150 # ms, when a press goes from a dit to a dah
CHAR_THRESHOLD: 225 # ms, post-release, when to cut off a letter and add it to the message
WORD_THRESHOLD: 1000 # ms, post-release, when to add a space
MESSAGE_THRESHOLD: 2500 # ms, post-release, when a message is complete

TRANSMIT_MODE_DURATION: 5.0 # sec, duration of transmit mode input acceptance
TRANSMIT_MODE_THRESHOLD: 0.5 # sec, time before transmit mode starts

FLASH_INTERVAL: 0.05 # seconds of flash interval
INITIALIZE_FLASHES: 3 # LED flashes on intialization
WORD_FLASHES: 1 # LED flashes on word completion
MESSAGE_FLASHES: 3 # LED flashes on message completion
TRANSMITTED_FLASHES: 5 # number of LED flashes on successful transmission

TWITTER_ENABLED: true # whether Twitter integration is enabled
