# Twitter Application Configuration
API_KEY: "API_OR_CONSUMER_KEY_HERE"
API_SECRET: "API_OR_CONSUMER_SECRET_HERE"

# Twitter User Account Configuration
ACCESS_TOKEN: "ACCESS_TOKEN_HERE"
ACCESS_TOKEN_SECRET: "ACCESS_TOKEN_SECRET_HERE"
